##
# @file colour_message.cmake
# @author Bruno Klopott
# @brief Function to print a coloured message to the console
#

string(ASCII 27 Escape)
set(Reset       "${Escape}[m")
set(Bold        "${Escape}[1m")
set(Red         "${Escape}[31m")
set(Green       "${Escape}[32m")
set(Yellow      "${Escape}[33m")
set(Blue        "${Escape}[34m")
set(Magenta     "${Escape}[35m")
set(Cyan        "${Escape}[36m")
set(White       "${Escape}[37m")

function(colour_message)
	list(GET ARGV 0 message_type)
	list(GET ARGV 1 colour)

	list(GET ARGV 2 bold)

	if (${bold} STREQUAL BOLD)
		set(use_bold ON)
		list(REMOVE_AT ARGV 2)
	endif ()

	list(REMOVE_AT ARGV 1)
	list(REMOVE_AT ARGV 0)

	if (${colour}     STREQUAL RED)
		if (${use_bold})
			set(modifier "${Bold}${Red}")
		else ()
			set(modifier "${Red}")
		endif ()
	elseif (${colour} STREQUAL GREEN)
		if (${use_bold})
			set(modifier "${Bold}${Green}")
		else ()
			set(modifier "${Green}")
		endif ()
	elseif (${colour} STREQUAL YELLOW)
		if (${use_bold})
			set(modifier "${Bold}${Yellow}")
		else ()
			set(modifier "${Yellow}")
		endif ()
	elseif (${colour} STREQUAL BLUE)
		if (${use_bold})
			set(modifier "${Bold}${Blue}")
		else ()
			set(modifier "${Blue}")
		endif ()
	elseif (${colour} STREQUAL MAGENTA)
		if (${use_bold})
			set(modifier "${Bold}${Magenta}")
		else ()
			set(modifier "${Magenta}")
		endif ()
	elseif (${colour} STREQUAL CYAN)
		if (${use_bold})
			set(modifier "${Bold}${Cyan}")
		else ()
			set(modifier "${Cyan}")
		endif ()
	elseif (${colour} STREQUAL WHITE)
		if (${use_bold})
			set(modifier "${Bold}${White}")
		else ()
			set(modifier "${White}")
		endif ()
	else (${colour})
		if (${use_bold})
			set(modifier "${Bold}")
		else ()
			set(modifier "")
		endif ()
	endif ()

	message(${message_type} "${modifier}${ARGV}${Reset}")
endfunction()
